Added support for bing.com
ChrisTruncer/Just-Metadata pull request #31
Opened 2016-09-14 21:32 UTC by xme

Hi Chris,

For my day 2 day job, I've to search for websites hosted behind a specific IP. I added a module to extract hostnames using the "IP=<ip>" query in Bing. The user needs a Bing API key.

/x

2016-09-15 18:34 UTC, ChrisTruncer commented
This looks awesome!  Thanks for sending this over, I'll get checking it out.

2016-09-15 21:08 UTC, ChrisTruncer commented on common/orchestra.py
> +                    print helpers.color("\nExport file saved to disk at " + f)
Can you move this print statement out of the for loop?  Right now it prints to the console for each IP loaded into Just-Metadata.

2016-09-15 21:11 UTC, ChrisTruncer requested changes
I only have the one small request for moving the print statement out of the for loop.

Thanks for getting this sent over.

2016-09-16 07:31 UTC, xme commented
Stupid me :) Fixed.

2016-09-16 16:19 UTC, ChrisTruncer approved these changes

2016-09-16 16:20 UTC, ChrisTruncer commented
Merging this in, thanks for the contribution!

2016-09-16 16:20 UTC, merged